### ISSUE TITLE
Linking error on mac 10.13.4

### ISSUE THREAD

**Issue by lmanchanda75** [vsubhash/amv-ffmpeg#2]
Error linking due to _ff_get_mb_score not found

**Comment by lmanchanda75** [comment]
Could solve the problem by finding and removing **inline** clause from the function definition

**Comment by twhitman** [comment]
@lmanchanda75 - Can you elaborate on the fix you found? I've run into the same error but cannot find a reference to _ff_get_mb_score in the code. Thanks!
